language: r
sudo: false
cache: packages

env:
  matrix:
    -R=devel COVERAGE=true
    -R=release

r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"
warnings_are_errors: false

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev

r_binary_packages:
  - devtools
  - curl

r_github_packages:
  - jimhester/covr


# report to codecov
after_success:
  - if [[ ! -z "$COVERAGE" ]];then Rscript -e 'covr::codecov(exclusions = list("R/ppdb.R"), quiet = FALSE)'; fi

# report to maintainer
notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: change
    on_failure: change

