language: R
sudo: false
cache: packages

r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"

matrix:
  r:
    - release
    - devel COVERAGE=true

env:
  - _R_CHECK_TIMINGS_="0"


# report to coveralls
after_success:
  - if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov(exclusions = list("R/ppdb.R"), quiet = FALSE)'; fi

# report to maintainer
notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: change
    on_failure: change

