language: r
sudo: false
cache: packages

r:
  - devel

r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"
warnings_are_errors: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

r_github_packages:
  - jimhester/covr
  - jeroenooms/curl


# report to coveralls
after_success:
  - Rscript -e 'covr::codecov(exclusions = list("R/ppdb.R"), quiet = FALSE)'
#  - if [[ ! -z "$COVERAGE" ]];then Rscript -e 'covr::codecov(exclusions = list("R/ppdb.R"), quiet = FALSE)'; fi

# report to maintainer
notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: change
    on_failure: change

