language: r
sudo: required
cache: packages

r:
  - devel
#  - release

env:
  global:
    - _R_CRAN_CHECK_INCOMING_=false


r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"
warnings_are_errors: false
r_check_revdep: false

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - openjdk-7-jre

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server

r_packages:
  - devtools
  - xml2

r_github_packages:
  - jimhester/covr
  - jeroenooms/curl

# report to codecov
after_success:
  - Rscript -e 'covr::codecov(exclusions = list("R/ppdb.R"), quiet = FALSE)'

# report to maintainer
notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: change
    on_failure: change

