language: r
sudo: required

r_github_packages:
 - jimhester/covr
 - jeroenooms/curl
 - jimhester/robustr

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: never
    on_failure: always
