language: r
sudo: required

r_github_packages:
 - jimhester/covr
 - jeroenooms/curl

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
email:
recipients:
- szoecs@uni-landau.de
on_success: never
on_failure: always
# One can also restrict the branches to test, see
# http://about.travis-ci.org/docs/user/build-configuration/#Specify-branches-to-build
branches:
only:
- master
