platform: x64

environment:
  R_ARCH: x64
  R_BUILD_ARGS: --no-manual
  R_CHECK_ARGS: --no-build-vignettes --no-manual --timings --as-cran --no-multiarch --no-examples
  R_INSTALL_ARGS: --no-multiarch
  PKGTYPE: binary
  NOT_CRAN: true

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
#  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0\jre
#  - set PATH=C:\Program Files (x86)\Java\jdk1.8.0\bin;C:\Program Files (x86)\Java\jdk1.8.0\jre\bin\server;%PATH%
#  - ls "C:\Program Files (x86)\Java\jdk1.8.0\jre"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

notifications:
  - provider: Email
    to:
      - scottericr@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: tar

  - path: '\*_*.zip'
    name: zip

  - path: '*.Rcheck\**\*.timings'
    name: Logs
